'use strict';
const $=s=>document.querySelector(s),fmt=n=>n==null?'—':Number(n||0).toLocaleString();
const categories=[['publication_hold','Publication holds'],['duplicate_identity','Shared source IDs'],['possible_duplicate','Possible duplicates'],['coordinates','Location problems'],['failed_jobs','Failed jobs'],['classification','Classification review'],['missing_evidence','Missing source evidence'],['stale','Enrichment >90 days'],['never_enriched','Never enriched'],['missing_menu','Missing menu link'],['failed','Enrichment failures']];
const state={data:null,category:'publication_hold',entity:'all',search:'',page:0,selected:null};
const el=(tag,text,className)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(className)n.className=className;return n;};
const safeUrl=value=>{try{const u=new URL(value);return /^https?:$/.test(u.protocol)&&!u.username&&!u.password?u.href:null;}catch{return null;}};
const entities=()=>state.data.entities.filter(e=>state.entity==='all'||e.entity===state.entity);
function rows(){let data;if(state.category==='failed_jobs')data=state.data.queue.failures?.filter(r=>state.entity==='all'||r.place_type===state.entity).map(r=>({...r,entity:r.place_type,name:`${r.job_type} job ${r.id}`,detail:r.last_error,google_place_id:r.osm_id,job:true}))||[];else data=entities().flatMap(e=>(e.issues[state.category]||[]).map(r=>({...r,entity:e.entity})));const q=state.search.toLowerCase();return data.filter(r=>[r.name,r.id,r.state,r.google_place_id,r.publicName].join(' ').toLowerCase().includes(q));}
function count(kind){if(kind==='failed_jobs'&&!state.data.queue.available)return null;if(kind==='failed_jobs')return (state.data.queue.counts||[]).filter(r=>r.status==='failed'&&(state.entity==='all'||r.place_type===state.entity)).reduce((s,r)=>s+r.count,0);return entities().reduce((s,e)=>s+(e.totals[kind]||0),0);}
function detail(r){const box=$('#detail');box.replaceChildren();if(!r){box.append(el('p','No finding selected.'));return;}box.append(el('span',r.entity.toUpperCase(),'tag'),el('span',r.job?'JOB '+r.id:'RECORD '+r.id,'tag'),el('h2',r.name),el('p',r.detail,'reason'));const dl=el('dl');for(const [k,v] of [['State',r.state],['External ID',r.google_place_id],['Coordinates',r.lat!=null?`${r.lat}, ${r.lng}`:null],['Last enriched',r.last_enriched_at?new Date(r.last_enriched_at).toLocaleString():null],['Source records',r.source_count],['Source observed',r.evidence_at?new Date(r.evidence_at).toLocaleString():null],['Style',r.style],['Confidence',r.style_confidence],['Related IDs',r.relatedIds?.join(', ')],['Attempts',r.attempts]])if(v!=null&&v!==''){dl.append(el('dt',k),el('dd',String(v)));}box.append(dl);if(r.publicId)box.append(el('p',`Protected public record: ${r.publicName} (#${r.publicId}). ${String(r.publicId)!==String(r.id)?'This is a different identity; do not merge its reviews into the imported restaurant.':'Publication stays blocked until its identity is verified.'}`,'protected'));const links=el('div',null,'links');const addLink=(label,url)=>{const href=safeUrl(url);if(!href)return;const a=el('a',label,'button');a.href=href;a.target='_blank';a.rel='noopener noreferrer';links.append(a);};addLink('Source evidence',r.source_url);addLink('Official website',r.website_url);if(r.lat!=null&&r.lng!=null)addLink('View coordinates',`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(r.lat+','+r.lng)}`);if(r.publicId)addLink('Protected review',`https://www.apizzamichigan.com/${r.entity==='taco'?'tacos/':''}places/${r.publicId}`);addLink('Search source reviews',`https://www.apizzamichigan.com/admin/reviews/data?entity=${r.entity}&focus=all&q=${encodeURIComponent((r.job?r.google_place_id:r.name)||r.google_place_id||'')}&queue=${state.category.includes('duplicate')?'duplicates':'matches'}`);box.append(links);if(r.job)box.append(el('p','Review the failure and its source before retrying the job.','note'));else if(state.category==='publication_hold')box.append(el('p','Record an identity decision before releasing this publication hold. The dashboard is read-only.','note'));}
function updateFreshness(){if(!state.data)return;const data=state.data;const age=(Date.now()-Date.parse(data.generatedAt))/3600000;$('#freshness').textContent=`${age>data.staleAfterHours?'Stale snapshot':'Snapshot'} · ${age<1?Math.max(0,Math.round(age*60))+' min':Math.round(age)+'h'} ago`;}
setInterval(updateFreshness,60000);
function render(){if(!state.data)return;const data=state.data;$('#metrics').replaceChildren(...[['Records scanned',entities().reduce((s,e)=>s+e.totals.records,0)],['Publication holds',count('publication_hold')],['Failed jobs',count('failed_jobs')]].map(([label,n])=>{const d=el('div',null,'metric');d.append(el('strong',fmt(n)),el('span',label));return d;}));$('#scope').textContent=`${new Date(data.generatedAt).toLocaleString()} · local canonical data + processing queue`;
updateFreshness();
$('#categories').replaceChildren(...categories.map(([id,label])=>{const b=el('button');b.setAttribute('aria-pressed',String(id===state.category));b.append(el('span',label),el('span',fmt(count(id)),'count'));b.onclick=()=>{state.category=id;state.page=0;state.selected=null;render();};return b;}));
const filtered=rows(),pages=Math.max(1,Math.ceil(filtered.length/20));state.page=Math.min(state.page,pages-1);const visible=filtered.slice(state.page*20,(state.page+1)*20);$('#rows').replaceChildren();const key=r=>r.entity+':'+r.id+':'+r.detail;if(!filtered.some(r=>key(r)===state.selected))state.selected=visible[0]?key(visible[0]):null;
for(const r of visible){const b=el('button',null,'finding');b.setAttribute('aria-current',String(key(r)===state.selected));b.append(el('strong',r.name),el('small',`${r.entity.toUpperCase()} · #${r.id}${r.state?' · '+r.state:''}`),el('small',r.detail));b.onclick=()=>{state.selected=key(r);render();if(matchMedia('(max-width:1100px)').matches)$('#detail').scrollIntoView({behavior:'smooth',block:'start'});};$('#rows').append(b);}if(!visible.length)$('#rows').append(el('p',state.search?'No sampled findings match this search.':'No findings in this snapshot.','empty'));detail(filtered.find(r=>key(r)===state.selected));$('#page').textContent=`${state.page+1} / ${pages}`;$('#prev').disabled=state.page===0;$('#next').disabled=state.page>=pages-1;$('#coverage').textContent=`${fmt(count(state.category))} total flags · ${fmt(filtered.length)} ${state.search?'matching ':''}sampled findings. ${state.category==='publication_hold'?'All active holds included.':'Up to 150 examples per category and product; search applies to those examples.'}`;$('#foot').textContent=`${data.scope} ${data.errors?.map(e=>e.message).join(' ')||''} Reload reads the latest exported snapshot; it does not run enrichment.`;}
async function load(){const b=$('#reload');b.disabled=true;try{if(location.protocol==='file:'){const embedded=document.getElementById('quality-data');if(!embedded)throw Error('Open through a local server or build a standalone report');state.data=JSON.parse(embedded.textContent);render();return;}const response=await fetch('restaurant-quality.json?at='+Date.now(),{cache:'no-store'});if(!response.ok)throw Error('Snapshot request failed ('+response.status+')');const data=await response.json();if(!Array.isArray(data.entities)||!Number.isFinite(Date.parse(data.generatedAt)))throw Error('Invalid snapshot');state.data=data;$('#error').hidden=true;render();}catch(error){$('#error').textContent=error.message+'. The previous snapshot, if present, remains visible.';$('#error').hidden=false;$('#freshness').textContent='Snapshot unavailable';}finally{b.disabled=false;}}
$('#entity').onchange=e=>{state.entity=e.target.value;state.page=0;state.selected=null;render();};$('#search').oninput=e=>{state.search=e.target.value;state.page=0;state.selected=null;render();};$('#prev').onclick=()=>{state.page--;render();};$('#next').onclick=()=>{state.page++;render();};$('#reload').onclick=()=>location.protocol==='file:'?location.reload():load();$('#export').onclick=()=>{if(!state.data)return;const fields=['entity','id','name','state','detail','google_place_id','source_url','website_url'];const quote=v=>'"'+String(v??'').replaceAll('"','""').replace(/^[=+@-]/,"'$&")+'"';const csv=[fields.join(','),...rows().map(r=>fields.map(f=>quote(r[f])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=el('a');a.href=url;a.download=`restaurant-quality-${state.category}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};load();
