import { defineInertProfile } from "@map-pipeline/sdk";

export const buildHereCityProfile = defineInertProfile({
  id: "builthere-city",
  policyVersion: 1,
  deploymentEnabled: false,
  sources: [
    {
      id: "builthere-detroit-arcgis-v1",
      adapter: "arcgis",
      namespace: "detroit-bseed",
      artifactPolicy: "forbidden",
      authority: "official",
      policyStatus: "pending",
      termsRef: null,
      retentionDays: null,
      upstreamTermsRefs: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "required",
        rawMaxDays: 30,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "source",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
    {
      id: "builthere-ann-arbor-arcgis-v1",
      adapter: "arcgis",
      namespace: "ann-arbor-plancases",
      artifactPolicy: "forbidden",
      authority: "official",
      policyStatus: "pending",
      termsRef: null,
      retentionDays: null,
      upstreamTermsRefs: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "required",
        rawMaxDays: 30,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "source",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
    {
      id: "builthere-community-tip-decisions-v1",
      adapter: "postgres",
      namespace: "builthere-tip-review",
      artifactPolicy: "forbidden",
      authority: "review_decision",
      policyStatus: "pending",
      termsRef: null,
      retentionDays: null,
      upstreamTermsRefs: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "derived_only",
        rawMaxDays: 0,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "source",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
  ],
  targetContract: {
    ownerRepository: "builthere.city",
    contractName: "builthere-pipeline-write-contract",
    supportedVersions: [],
    digest: null,
  },
  pluginLockDigest: null,
  invariants: [
    "official and community identities remain separate in version 1",
    "writes are changed-only and do not clear nulls without an explicit action",
    "tip submitter PII never enters ordinary artifacts or logs",
    "tip approval is not published until a verified receipt exists",
    "apply remains blocked until the app publishes a pinned write contract",
  ],
  effectPolicy: [],
});
