import { defineInertProfile } from "@map-pipeline/sdk";

export * from "./candidate-v1.js";
export * from "./fsq-preview.js";
export * from "./fsq-release-v1.js";
export * from "./fsq-shadow-v1.js";
export * from "./matching-v1.js";

export const apizzaMichiganProfile = defineInertProfile({
  id: "apizzamichigan",
  policyVersion: 1,
  deploymentEnabled: false,
  sources: [
    {
      id: "apizza-osm-v1",
      adapter: "osm",
      namespace: "openstreetmap",
      artifactPolicy: "forbidden",
      authority: "discovery_only",
      policyStatus: "pending",
      termsRef: null,
      attributionRef: null,
      retentionDays: null,
      resourceUris: [],
      allowedSchemas: [],
      upstreamTerms: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "required",
        rawMaxDays: 30,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "source",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
    {
      id: "apizza-fsq-v1",
      adapter: "process",
      namespace: "foursquare",
      artifactPolicy: "forbidden",
      authority: "discovery_only",
      policyStatus: "pending",
      termsRef: null,
      attributionRef: null,
      retentionDays: null,
      resourceUris: [],
      allowedSchemas: [],
      upstreamTerms: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "derived_only",
        rawMaxDays: 0,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "source",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
    {
      id: "apizza-overture-v1",
      adapter: "process",
      namespace: "overture",
      artifactPolicy: "forbidden",
      authority: "discovery_only",
      policyStatus: "pending",
      termsRef: null,
      attributionRef: null,
      retentionDays: null,
      resourceUris: [],
      allowedSchemas: [],
      upstreamTerms: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "required",
        rawMaxDays: 30,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "source",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
    {
      id: "apizza-atp-v1",
      adapter: "files",
      namespace: "atp",
      artifactPolicy: "forbidden",
      authority: "discovery_only",
      policyStatus: "pending",
      termsRef: null,
      attributionRef: null,
      retentionDays: null,
      resourceUris: [],
      allowedSchemas: [],
      upstreamTerms: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "derived_only",
        rawMaxDays: 0,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "per_child",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
    {
      id: "apizza-wikidata-v1",
      adapter: "network",
      namespace: "wikidata",
      artifactPolicy: "forbidden",
      authority: "discovery_only",
      policyStatus: "pending",
      termsRef: null,
      attributionRef: null,
      retentionDays: null,
      resourceUris: [],
      allowedSchemas: [],
      upstreamTerms: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "required",
        rawMaxDays: 30,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "source",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
    {
      id: "apizza-official-website-v1",
      adapter: "official-website",
      namespace: "official-website",
      artifactPolicy: "forbidden",
      authority: "discovery_only",
      policyStatus: "pending",
      termsRef: null,
      attributionRef: null,
      retentionDays: null,
      resourceUris: [],
      allowedSchemas: [],
      upstreamTerms: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "derived_only",
        rawMaxDays: 0,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "source",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
  ],
  shadowSources: [
    {
      stageId: "fsq-source",
      pluginId: "apizza-fsq-ephemeral-source-v1",
      policyId: "shadow:apizza-fsq-os-places-flatfile-v1",
      adapter: "json-file-snapshot",
      effectClass: "artifact.read",
      resourceUri: "file-snapshot://pipeline-input/apizza-fsq-os-places-release-v1",
      operations: ["snapshot"],
      outputPorts: ["rows"],
      artifactClass: "raw",
      activationEligible: false,
    },
    {
      stageId: "canonical-source",
      pluginId: "apizza-canonical-postgres-source-v1",
      policyId: "shadow:apizza-canonical-read-v1",
      adapter: "postgres-readonly",
      effectClass: "network.read",
      resourceUri: "postgres-view://pipeline-input/apizza-canonical-match-v1",
      operations: ["snapshot"],
      outputPorts: ["canonical"],
      artifactClass: "derived",
      activationEligible: false,
    },
  ],
  targetContract: {
    ownerRepository: "Antwohlf/apizzamichigan",
    contractName: "apizza-pipeline-write-contract",
    supportedVersions: [],
    digestKind: "sha256-canonical-json-v1",
    digest: null,
  },
  observedTargetContract: {
    ownerRepository: "Antwohlf/apizzamichigan",
    contractName: "apizza-pipeline-write-contract",
    version: 1,
    profile: "apizzamichigan",
    entity: "pizza",
    rawByteDigest: "sha256:41a0c211e9f8c474b6487c1b6e4181e2cf8a9db7bc2561de2513a503cdbb96b0",
    byteLength: 3343,
    activationEligible: false,
    source: {
      repository: "Antwohlf/apizzamichigan",
      revision: "ecfb0fd57e1a25384a7d81ad78f1e8d16b205728",
      path: "contracts/pipeline-targets/apizza-pipeline-write-contract.v1.json",
      digestKind: "sha256-raw-bytes-v1",
    },
  },
  pluginLockDigest: null,
  invariants: [
    "discovery cannot write public tables",
    "unreviewed identity and editorial fields cannot publish",
    "pizza job and checkpoint namespaces never overlap taco",
  ],
  effectPolicy: [],
});
