import { defineInertProfile } from "@map-pipeline/sdk";

export const apizzaMichiganProfile = defineInertProfile({
  id: "apizzamichigan",
  policyVersion: 1,
  deploymentEnabled: false,
  sources: [
    {
      id: "apizza-osm-v1",
      adapter: "osm",
      namespace: "openstreetmap",
      artifactPolicy: "forbidden",
      authority: "discovery_only",
      policyStatus: "pending",
      termsRef: null,
      retentionDays: null,
      upstreamTermsRefs: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "required",
        rawMaxDays: 30,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "source",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
    {
      id: "apizza-fsq-v1",
      adapter: "process",
      namespace: "foursquare",
      artifactPolicy: "forbidden",
      authority: "discovery_only",
      policyStatus: "pending",
      termsRef: null,
      retentionDays: null,
      upstreamTermsRefs: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "derived_only",
        rawMaxDays: 0,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "source",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
    {
      id: "apizza-overture-v1",
      adapter: "process",
      namespace: "overture",
      artifactPolicy: "forbidden",
      authority: "discovery_only",
      policyStatus: "pending",
      termsRef: null,
      retentionDays: null,
      upstreamTermsRefs: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "required",
        rawMaxDays: 30,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "source",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
    {
      id: "apizza-atp-v1",
      adapter: "files",
      namespace: "atp",
      artifactPolicy: "forbidden",
      authority: "discovery_only",
      policyStatus: "pending",
      termsRef: null,
      retentionDays: null,
      upstreamTermsRefs: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "derived_only",
        rawMaxDays: 0,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "per_child",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
    {
      id: "apizza-wikidata-v1",
      adapter: "network",
      namespace: "wikidata",
      artifactPolicy: "forbidden",
      authority: "discovery_only",
      policyStatus: "pending",
      termsRef: null,
      retentionDays: null,
      upstreamTermsRefs: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "required",
        rawMaxDays: 30,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "source",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
    {
      id: "apizza-official-website-v1",
      adapter: "official-website",
      namespace: "official-website",
      artifactPolicy: "forbidden",
      authority: "discovery_only",
      policyStatus: "pending",
      termsRef: null,
      retentionDays: null,
      upstreamTermsRefs: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "derived_only",
        rawMaxDays: 0,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "source",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
  ],
  targetContract: {
    ownerRepository: "apizzamichigan",
    contractName: "apizza-pipeline-write-contract",
    supportedVersions: [],
    digest: null,
  },
  pluginLockDigest: null,
  invariants: [
    "discovery cannot write public tables",
    "unreviewed identity and editorial fields cannot publish",
    "pizza job and checkpoint namespaces never overlap taco",
  ],
  effectPolicy: [],
});
