import { defineInertProfile } from "@map-pipeline/sdk";

export const tacoBoutMichiganProfile = defineInertProfile({
  id: "tacoboutmichigan",
  policyVersion: 1,
  deploymentEnabled: false,
  sources: [
    {
      id: "taco-osm-v1",
      adapter: "osm",
      namespace: "openstreetmap",
      artifactPolicy: "forbidden",
      authority: "discovery_only",
      policyStatus: "pending",
      termsRef: null,
      attributionRef: null,
      retentionDays: null,
      resourceUris: [],
      allowedSchemas: [],
      upstreamTerms: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "required",
        rawMaxDays: 30,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "source",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
    {
      id: "taco-fsq-v1",
      adapter: "process",
      namespace: "foursquare",
      artifactPolicy: "forbidden",
      authority: "discovery_only",
      policyStatus: "pending",
      termsRef: null,
      attributionRef: null,
      retentionDays: null,
      resourceUris: [],
      allowedSchemas: [],
      upstreamTerms: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "derived_only",
        rawMaxDays: 0,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "source",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
    {
      id: "taco-overture-v1",
      adapter: "process",
      namespace: "overture",
      artifactPolicy: "forbidden",
      authority: "discovery_only",
      policyStatus: "pending",
      termsRef: null,
      attributionRef: null,
      retentionDays: null,
      resourceUris: [],
      allowedSchemas: [],
      upstreamTerms: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "required",
        rawMaxDays: 30,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "source",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
    {
      id: "taco-official-website-v1",
      adapter: "official-website",
      namespace: "official-website",
      artifactPolicy: "forbidden",
      authority: "discovery_only",
      policyStatus: "pending",
      termsRef: null,
      attributionRef: null,
      retentionDays: null,
      resourceUris: [],
      allowedSchemas: [],
      upstreamTerms: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "derived_only",
        rawMaxDays: 0,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "source",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
  ],
  shadowSources: [],
  targetContract: {
    ownerRepository: "Antwohlf/apizzamichigan",
    contractName: "taco-pipeline-write-contract",
    supportedVersions: [],
    digestKind: "sha256-canonical-json-v1",
    digest: null,
  },
  observedTargetContract: {
    ownerRepository: "Antwohlf/apizzamichigan",
    contractName: "taco-pipeline-write-contract",
    version: 1,
    profile: "tacoboutmichigan",
    entity: "taco",
    rawByteDigest: "sha256:2820447773a46e6d8a8cb0187a6e329e4241a65632506b3b70055113c9bab21d",
    byteLength: 3241,
    activationEligible: false,
    source: {
      repository: "Antwohlf/apizzamichigan",
      revision: "ecfb0fd57e1a25384a7d81ad78f1e8d16b205728",
      path: "contracts/pipeline-targets/taco-pipeline-write-contract.v1.json",
      digestKind: "sha256-raw-bytes-v1",
    },
  },
  pluginLockDigest: null,
  invariants: [
    "taco source authority is independent from pizza source authority",
    "sharing the OSM adapter does not share configuration or policy",
    "current Taco target migrations are owned by apizzamichigan until extracted",
    "taco job and checkpoint namespaces never overlap pizza",
    "new writes remain disabled until fenced cutover; legacy Taco stays authoritative",
  ],
  effectPolicy: [],
});
