import { defineInertProfile } from "@map-pipeline/sdk";

export const tacoBoutMichiganProfile = defineInertProfile({
  id: "tacoboutmichigan",
  policyVersion: 1,
  deploymentEnabled: false,
  sources: [
    {
      id: "taco-osm-v1",
      adapter: "osm",
      namespace: "openstreetmap",
      artifactPolicy: "forbidden",
      authority: "discovery_only",
      policyStatus: "pending",
      termsRef: null,
      attributionRef: null,
      retentionDays: null,
      resourceUris: [],
      allowedSchemas: [],
      upstreamTerms: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "required",
        rawMaxDays: 30,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "source",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
    {
      id: "taco-fsq-v1",
      adapter: "process",
      namespace: "foursquare",
      artifactPolicy: "forbidden",
      authority: "discovery_only",
      policyStatus: "pending",
      termsRef: null,
      attributionRef: null,
      retentionDays: null,
      resourceUris: [],
      allowedSchemas: [],
      upstreamTerms: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "derived_only",
        rawMaxDays: 0,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "source",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
    {
      id: "taco-overture-v1",
      adapter: "process",
      namespace: "overture",
      artifactPolicy: "forbidden",
      authority: "discovery_only",
      policyStatus: "pending",
      termsRef: null,
      attributionRef: null,
      retentionDays: null,
      resourceUris: [],
      allowedSchemas: [],
      upstreamTerms: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "required",
        rawMaxDays: 30,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "source",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
    {
      id: "taco-official-website-v1",
      adapter: "official-website",
      namespace: "official-website",
      artifactPolicy: "forbidden",
      authority: "discovery_only",
      policyStatus: "pending",
      termsRef: null,
      attributionRef: null,
      retentionDays: null,
      resourceUris: [],
      allowedSchemas: [],
      upstreamTerms: [],
      provisionalRetention: {
        postApprovalArtifactPolicy: "derived_only",
        rawMaxDays: 0,
        derivedMaxDays: 30,
        reviewEvidenceAfterTerminalDays: 30,
        auditMetadata: "durable_minimal",
        upstreamTermsMode: "source",
      },
      allowedFields: [],
      redistribution: "forbidden",
    },
  ],
  targetContract: {
    ownerRepository: "apizzamichigan",
    contractName: "taco-pipeline-write-contract",
    supportedVersions: [],
    digest: null,
  },
  pluginLockDigest: null,
  invariants: [
    "taco source authority is independent from pizza source authority",
    "sharing the OSM adapter does not share configuration or policy",
    "current Taco target migrations are owned by apizzamichigan until extracted",
    "taco job and checkpoint namespaces never overlap pizza",
    "new writes remain disabled until fenced cutover; legacy Taco stays authoritative",
  ],
  effectPolicy: [],
});
